arch:
  - arm64
  - ppc64le
  - s390x
branches:
  only:
    - master
language: node_js
node_js:
  - 8.11.1
  - 10
  - 12
  - 14
  - 16
  - 17
before_install: |
  NODEJS_VERSION=$(node --version)
  NODEJS_MAJOR_VERSION=${NODEJS_VERSION%%.*}
  if [ 'v8' == "$NODEJS_MAJOR_VERSION" ]
  then
    npm install --global npm@5
  elif [ 'v10' == "$NODEJS_MAJOR_VERSION" ]
  then
    npm install --global npm@7
  elif [ 'v17' != "$NODEJS_MAJOR_VERSION" ]
  then
    npm install --global npm@8
  fi
script:
  - npm run --ignore-scripts build
  - npm test --ignore-scripts
